'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'kn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // English translations
    'welcome': 'Get Ready to make a difference!',
    'welcome_subtitle': 'Get Ready to make a difference! Get Ready to make a difference! Get Ready to make a difference!',
    'next': 'NEXT',
    'available_donations': 'AVAILABLE DONATIONS',
    'view_more': '+ View More',
    'show_less': '- Show Less',
    'community': 'COMMUNITY',
    'orders_delivered': 'Orders delivered',
    'feedback_received': 'Feedback received',
    'points_earned': 'Points earned',
    'welcome_volunteer': 'WELCOME VOLUNTEER',
    'donation_details': 'Donation Details',
    'donation_information': 'DONATION INFORMATION',
    'delivery_action': 'DELIVERY ACTION',
    'important_notes': 'Important Notes',
    'verify_food_quality': 'Please verify the food quality before accepting',
    'check_expiry_date': 'Check the expiry date and storage conditions',
    'ensure_proper_handling': 'Ensure proper handling during transportation',
    'deliver_this_donation': 'DELIVER THIS DONATION',
    'cancel': 'CANCEL',
    'confirm': 'CONFIRM',
    'title': 'Title',
    'description': 'Description',
    'location': 'Location',
    'veg_quantity': 'Veg Quantity',
    'non_veg_quantity': 'Non-Veg Quantity',
    'preparation_date': 'Preparation Date',
    'expiry_date': 'Expiry Date',
    'are_you_sure': 'Are you sure you want to deliver food from',
    'to': 'to',
    // Role selection translations
    'select_role': 'Select Your Role',
    'select_role_description': 'Choose how you\'d like to participate in our food sharing community',
    'donor': 'DONOR',
    'volunteer': 'VOLUNTEER',
    'receiver': 'RECEIVER',
    'donor_description': 'Share your excess food with those in need and make a difference in your community.',
    'volunteer_description': 'Help bridge the gap by delivering food from donors to those who need it most.',
    'receiver_description': 'Connect with food donors and access available food resources in your area.',
    'continue': 'CONTINUE',
    'donor_details': 'Donor Details',
    'restaurant': 'RESTAURANT',
    'events': 'EVENTS',
    'individual': 'INDIVIDUAL',
    'organization_name': 'Organization/ Business Name',
    'delivery_provision': 'Delivery Provision',
    'phone_number': 'Phone Number',
    'email_address': 'Email Address',
    'address': 'Address',
    'pin_code': 'Pin Code',
    'use_current_location': 'Use current location',
    'enter_phone': 'Enter 10 digit number',
    'fill_required_fields': 'Please fill in all required fields',
    'valid_phone_number': 'Please enter a valid 10-digit phone number',
    'valid_email': 'Please enter a valid email address',
    'fill_address_pincode': 'Please fill in both address and pin code to proceed',
    'welcome_donor': 'WELCOME DONOR',
    'total_donations': 'Total donations',
    'donations_received': 'Donations received',
    'people_reached': 'People reached',
    'extra_food_message': 'Got extra food? Share it with those in need!',
    'create_donation_post': 'Create Donation Post',
    'donation_history': 'DONATION HISTORY',
    'discussion': 'DISCUSSION',
    'announcement': 'ANNOUNCEMENT',
    'pending': 'Pending',
    'donated': 'Donated',
    'chapati': 'Chapati',
    'daal': 'Daal',
    'rice': 'Rice',
    // Donor Create Page
    'create_donation': 'Create Donation',
    'add_title': 'Add Title',
    'food_title': 'Food title',
    'ready_to_pickup': 'Is it ready to pick up?',
    'select_availability': 'Select Availability',
    'available': 'Available',
    'not_available': 'Not Available',
    'not_ready_to_pickup': 'Not Ready to Pick Up',
    'describe_food_donation': 'Describe your food donation...',
    'food_quantity': 'Food Quantity',
    'veg': 'Veg',
    'non_veg': 'Non Veg',
    'photos': 'Photos',
    'food_quality_assurance': 'I assure that the food quality and hygiene has not been compromised',
    'submit': 'SUBMIT',
    'donation_success': 'Awesome! Your donation request posted Successfully',
    'back_to_home': 'BACK TO HOME',
    // Volunteer Home Page
    'welcome_volunteer': 'WELCOME VOLUNTEER',
    'orders_delivered': 'Orders delivered',
    'feedback_received': 'Feedback received',
    'points_earned': 'Points earned',
    'available_donations': 'AVAILABLE DONATIONS',
    'view_more': '+ View More',
    'show_less': '- Show Less',
    'community': 'COMMUNITY',
    'discussion': 'DISCUSSION',
    'announcement': 'ANNOUNCEMENT',
    'discussion_description': 'Hey everyone, I run a restaurant and often have leftover food at closing time. What are the best practices to ensure food is stored safely before donation',
    'announcement_description': "We have seen an increase in food donations, but we need more volunteers for pickup and delivery in Bengaluru. If you're interested, please sign up on our portal",
    'volunteer_details': 'Volunteer Details',
    'full_name': 'Full Name',
    'occupation': 'Occupation',
    'aadhar_id': 'Aadhar ID',
    // Receiver Home Page
    'requests_made': 'Requests made',
    'requests_fulfilled': 'Requests fulfilled',
    'people_helped': 'People helped',
    'user_login': 'User Login',
    'hero_title': 'Rescue. Share. Nourish.',
    'hero_subtitle': 'Because No Meal Should Go to Waste!',
    'need_meal_prompt': 'Know someone in need of a meal?',
    'create_food_request': 'Create Food Request',
    'request_history': 'REQUEST HISTORY',
    'food_request_details': 'Food Request Details',
    'no_of_beneficiaries': 'NO OF BENEFICIARIES',
    'enter_beneficiaries': 'Enter number of beneficiaries',
    'beneficiary_details': 'BENEFICIARY DETAILS (OPTIONAL)',
    'name': 'Name',
    'need_food_example': 'Eg: Need food for 50 people.',
    'contact_details': 'Contact Details',
    'request_success': 'Great! Your food request has been submitted successfully',
    'enter_full_name': 'Enter your full name',
    'enter_occupation': 'Enter your occupation',
    'enter_aadhar': 'Enter your Aadhar ID',
    'enter_address': 'Enter your address',
    'enter_pincode': 'Enter your pin code',
    'enter_org_name': 'Enter organization name',
    'enter_delivery_provision': 'Enter delivery provision details',
    'enter_email': 'Enter your email address',
    'personal_info': 'Personal Information',
    'organization_info': 'Organization Information',
    'address_info': 'Address Information',
  },
  hi: {
    // Hindi translations
    'welcome': 'अंतर लाने के लिए तैयार हो जाएं!',
    'welcome_subtitle': 'अंतर लाने के लिए तैयार हो जाएं! अंतर लाने के लिए तैयार हो जाएं! अंतर लाने के लिए तैयार हो जाएं!',
    'next': 'अगला',
    'available_donations': 'उपलब्ध दान',
    'view_more': '+ अधिक देखें',
    'show_less': '- कम दिखाएं',
    'community': 'समुदाय',
    'orders_delivered': 'डिलीवर किए गए ऑर्डर',
    'feedback_received': 'प्राप्त प्रतिक्रिया',
    'points_earned': 'अर्जित अंक',
    'welcome_volunteer': 'स्वागत है स्वयंसेवक',
    'donation_details': 'दान विवरण',
    'donation_information': 'दान जानकारी',
    'delivery_action': 'डिलीवरी कार्रवाई',
    'important_notes': 'महत्वपूर्ण नोट्स',
    'verify_food_quality': 'स्वीकार करने से पहले भोजन की गुणवत्ता की जांच करें',
    'check_expiry_date': 'समाप्ति तिथि और भंडारण स्थितियों की जांच करें',
    'ensure_proper_handling': 'परिवहन के दौरान उचित हैंडलिंग सुनिश्चित करें',
    'deliver_this_donation': 'इस दान को डिलीवर करें',
    'cancel': 'रद्द करें',
    'confirm': 'पुष्टि करें',
    'title': 'शीर्षक',
    'description': 'विवरण',
    'location': 'स्थान',
    'veg_quantity': 'शाकाहारी मात्रा',
    'non_veg_quantity': 'मांसाहारी मात्रा',
    'preparation_date': 'तैयारी की तारीख',
    'expiry_date': 'समाप्ति तिथि',
    'are_you_sure': 'क्या आप वाकई भोजन डिलीवर करना चाहते हैं',
    'to': 'से',
    // Role selection translations
    'select_role': 'अपनी भूमिका चुनें',
    'select_role_description': 'हमारे खाद्य साझाकरण समुदाय में भाग लेने के लिए चुनें',
    'donor': 'दाता',
    'volunteer': 'स्वयंसेवक',
    'receiver': 'प्राप्तकर्ता',
    'donor_description': 'अपने अतिरिक्त भोजन को जरूरतमंदों के साथ साझा करें और अपने समुदाय में बदलाव लाएं।',
    'volunteer_description': 'दाताओं से भोजन को जरूरतमंदों तक पहुंचाने में मदद करें।',
    'receiver_description': 'खाद्य दाताओं से जुड़ें और अपने क्षेत्र में उपलब्ध खाद्य संसाधनों तक पहुंच प्राप्त करें।',
    'continue': 'जारी रखें',
    'donor_details': 'दाता विवरण',
    'restaurant': 'रेस्तरां',
    'events': 'कार्यक्रम',
    'individual': 'व्यक्तिगत',
    'organization_name': 'संगठन/ व्यवसाय का नाम',
    'delivery_provision': 'डिलीवरी प्रावधान',
    'phone_number': 'फोन नंबर',
    'email_address': 'ईमेल पता',
    'address': 'पता',
    'pin_code': 'पिन कोड',
    'use_current_location': 'वर्तमान स्थान का उपयोग करें',
    'enter_phone': '10 अंकों का नंबर दर्ज करें',
    'fill_required_fields': 'कृपया सभी आवश्यक फ़ील्ड भरें',
    'valid_phone_number': 'कृपया एक वैध 10-अंक का फोन नंबर दर्ज करें',
    'valid_email': 'कृपया एक वैध ईमेल पता दर्ज करें',
    'fill_address_pincode': 'आगे बढ़ने के लिए कृपया पता और पिन कोड भरें',
    'welcome_donor': 'स्वागत है दाता',
    'total_donations': 'कुल दान',
    'donations_received': 'प्राप्त दान',
    'people_reached': 'लोगों तक पहुंचे',
    'extra_food_message': 'अतिरिक्त भोजन है? इसे जरूरतमंदों के साथ साझा करें!',
    'create_donation_post': 'दान पोस्ट बनाएं',
    'donation_history': 'दान इतिहास',
    'discussion': 'चर्चा',
    'announcement': 'घोषणा',
    'pending': 'लंबित',
    'donated': 'दान किया गया',
    'chapati': 'चपाती',
    'daal': 'दाल',
    'rice': 'चावल',
    // Donor Create Page
    'create_donation': 'दान बनाएं',
    'add_title': 'शीर्षक जोड़ें',
    'food_title': 'भोजन का शीर्षक',
    'ready_to_pickup': 'क्या यह लेने के लिए तैयार है?',
    'select_availability': 'उपलब्धता चुनें',
    'available': 'उपलब्ध',
    'not_available': 'उपलब्ध नहीं',
    'not_ready_to_pickup': 'लेने के लिए तैयार नहीं',
    'describe_food_donation': 'अपने भोजन दान का वर्णन करें...',
    'food_quantity': 'भोजन की मात्रा',
    'veg': 'शाकाहारी',
    'non_veg': 'मांसाहारी',
    'photos': 'फोटो',
    'food_quality_assurance': 'मैं आश्वस्त करता हूं कि भोजन की गुणवत्ता और स्वच्छता से समझौता नहीं किया गया है',
    'submit': 'जमा करें',
    'donation_success': 'बहुत बढ़िया! आपका दान अनुरोध सफलतापूर्वक पोस्ट किया गया',
    'back_to_home': 'होम पर वापस जाएं',
    'fill_required_fields': 'कृपया सभी आवश्यक फ़ील्ड भरें',
    'volunteer_details': 'स्वयंसेवक विवरण',
    'full_name': 'पूरा नाम',
    'occupation': 'व्यवसाय',
    'aadhar_id': 'आधार आईडी',
    // Volunteer Home Page
    'welcome_volunteer': 'स्वागत है स्वयंसेवक',
    'orders_delivered': 'डिलीवर किए गए ऑर्डर',
    'feedback_received': 'प्राप्त प्रतिक्रिया',
    'points_earned': 'अर्जित अंक',
    'available_donations': 'उपलब्ध दान',
    'view_more': '+ अधिक देखें',
    'show_less': '- कम दिखाएं',
    'community': 'समुदाय',
    'discussion': 'चर्चा',
    'announcement': 'घोषणा',
    'discussion_description': 'नमस्कार सभी को, मैं एक रेस्तरां चलाता हूं और बंद होने के समय अक्सर बचा हुआ खाना रह जाता है। दान करने से पहले भोजन को सुरक्षित रखने के लिए सर्वोत्तम प्रथाएं क्या हैं',
    'announcement_description': 'हमने खाद्य दान में वृद्धि देखी है, लेकिन बेंगलुरु में पिकअप और डिलीवरी के लिए हमें और स्वयंसेवकों की आवश्यकता है। यदि आप रुचि रखते हैं, तो कृपया हमारे पोर्टल पर साइन अप करें',
    // Receiver Home Page
    'requests_made': 'किए गए अनुरोध',
    'requests_fulfilled': 'पूरे किए गए अनुरोध',
    'people_helped': 'मदद किए गए लोग',
    'user_login': 'उपयोगकर्ता लॉगिन',
    'hero_title': 'बचाएं। साझा करें। पोषण करें।',
    'hero_subtitle': 'क्योंकि कोई भोजन बर्बाद नहीं होना चाहिए!',
    'need_meal_prompt': 'क्या आप किसी ऐसे व्यक्ति को जानते हैं जिसे भोजन की आवश्यकता है?',
    'create_food_request': 'भोजन अनुरोध बनाएं',
    'request_history': 'अनुरोध इतिहास',
    'food_request_details': 'भोजन अनुरोध विवरण',
    'no_of_beneficiaries': 'लाभार्थियों की संख्या',
    'enter_beneficiaries': 'लाभार्थियों की संख्या दर्ज करें',
    'beneficiary_details': 'लाभार्थी विवरण (वैकल्पिक)',
    'name': 'नाम',
    'need_food_example': 'उदाहरण: 50 लोगों के लिए भोजन की आवश्यकता है।',
    'contact_details': 'संपर्क विवरण',
    'request_success': 'बहुत बढ़िया! आपका भोजन अनुरोध सफलतापूर्वक जमा कर दिया गया है',
    'enter_full_name': 'अपना पूरा नाम दर्ज करें',
    'enter_occupation': 'अपना व्यवसाय दर्ज करें',
    'enter_aadhar': 'अपना आधार आईडी दर्ज करें',
    'enter_address': 'अपना पता दर्ज करें',
    'enter_pincode': 'अपना पिन कोड दर्ज करें',
    'enter_org_name': 'संगठन का नाम दर्ज करें',
    'enter_delivery_provision': 'डिलीवरी प्रावधान विवरण दर्ज करें',
    'enter_email': 'अपना ईमेल पता दर्ज करें',
    'personal_info': 'व्यक्तिगत जानकारी',
    'organization_info': 'संगठन की जानकारी',
    'address_info': 'पता जानकारी',
  },
  kn: {
    // Kannada translations
    'welcome': 'ವ್ಯತ್ಯಾಸ ಮಾಡಲು ಸಿದ್ಧರಾಗಿ!',
    'welcome_subtitle': 'ವ್ಯತ್ಯಾಸ ಮಾಡಲು ಸಿದ್ಧರಾಗಿ! ವ್ಯತ್ಯಾಸ ಮಾಡಲು ಸಿದ್ಧರಾಗಿ! ವ್ಯತ್ಯಾಸ ಮಾಡಲು ಸಿದ್ಧರಾಗಿ!',
    'next': 'ಮುಂದೆ',
    'available_donations': 'ಲಭ್ಯ ದಾನಗಳು',
    'view_more': '+ ಹೆಚ್ಚು ನೋಡಿ',
    'show_less': '- ಕಡಿಮೆ ತೋರಿಸಿ',
    'community': 'ಸಮುದಾಯ',
    'orders_delivered': 'ವಿತರಿಸಿದ ಆರ್ಡರ್‌ಗಳು',
    'feedback_received': 'ಸ್ವೀಕರಿಸಿದ ಪ್ರತಿಕ್ರಿಯೆ',
    'points_earned': 'ಗಳಿಸಿದ ಅಂಕಗಳು',
    'welcome_volunteer': 'ಸ್ವಾಗತ ಸ್ವಯಂಸೇವಕ',
    'donation_details': 'ದಾನ ವಿವರಗಳು',
    'donation_information': 'ದಾನ ಮಾಹಿತಿ',
    'delivery_action': 'ವಿತರಣೆ ಕ್ರಮ',
    'important_notes': 'ಪ್ರಮುಖ ಟಿಪ್ಪಣಿಗಳು',
    'verify_food_quality': 'ಸ್ವೀಕರಿಸುವ ಮೊದಲು ಆಹಾರದ ಗುಣಮಟ್ಟವನ್ನು ಪರಿಶೀಲಿಸಿ',
    'check_expiry_date': 'ಮುಕ್ತಾಯ ದಿನಾಂಕ ಮತ್ತು ಸಂಗ್ರಹಣೆ ಪರಿಸ್ಥಿತಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
    'ensure_proper_handling': 'ಸಾರಿಗೆ ಸಮಯದಲ್ಲಿ ಸರಿಯಾದ ನಿರ್ವಹಣೆಯನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ',
    'deliver_this_donation': 'ಈ ದಾನವನ್ನು ವಿತರಿಸಿ',
    'cancel': 'ರದ್ದುಮಾಡಿ',
    'confirm': 'ದೃಢೀಕರಿಸಿ',
    'title': 'ಶೀರ್ಷಿಕೆ',
    'description': 'ವಿವರಣೆ',
    'location': 'ಸ್ಥಳ',
    'veg_quantity': 'ಶಾಕಾಹಾರಿ ಪ್ರಮಾಣ',
    'non_veg_quantity': 'ಮಾಂಸಾಹಾರಿ ಪ್ರಮಾಣ',
    'preparation_date': 'ತಯಾರಿ ದಿನಾಂಕ',
    'expiry_date': 'ಮುಕ್ತಾಯ ದಿನಾಂಕ',
    'are_you_sure': 'ನೀವು ನಿಜವಾಗಿಯೂ ಆಹಾರವನ್ನು ವಿತರಿಸಲು ಬಯಸುವಿರಾ',
    'to': 'ನಿಂದ',
    // Role selection translations
    'select_role': 'ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'select_role_description': 'ನಮ್ಮ ಆಹಾರ ಹಂಚಿಕೆ ಸಮುದಾಯದಲ್ಲಿ ಭಾಗವಹಿಸಲು ಆಯ್ಕೆಮಾಡಿ',
    'donor': 'ದಾನಿ',
    'volunteer': 'ಸ್ವಯಂಸೇವಕ',
    'receiver': 'ಸ್ವೀಕರಿಸುವವರು',
    'donor_description': 'ನಿಮ್ಮ ಹೆಚ್ಚುವರಿ ಆಹಾರವನ್ನು ಅಗತ್ಯವಿರುವವರೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳಿ ಮತ್ತು ನಿಮ್ಮ ಸಮುದಾಯದಲ್ಲಿ ವ್ಯತ್ಯಾಸವನ್ನು ತರಿ.',
    'volunteer_description': 'ದಾನಿಗಳಿಂದ ಆಹಾರವನ್ನು ಅಗತ್ಯವಿರುವವರಿಗೆ ತಲುಪಿಸಲು ಸಹಾಯ ಮಾಡಿ.',
    'receiver_description': 'ಆಹಾರ ದಾನಿಗಳೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ ಮತ್ತು ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ ಲಭ್ಯವಿರುವ ಆಹಾರ ಸಂಪನ್ಮೂಲಗಳಿಗೆ ಪ್ರವೇಶ ಪಡೆಯಿರಿ.',
    'continue': 'ಮುಂದುವರೆಯಿರಿ',
    'donor_details': 'ದಾನಿ ವಿವರಗಳು',
    'restaurant': 'ರೆಸ್ಟೋರೆಂಟ್',
    'events': 'ಕಾರ್ಯಕ್ರಮಗಳು',
    'individual': 'ವೈಯಕ್ತಿಕ',
    'organization_name': 'ಸಂಸ್ಥೆ/ ವ್ಯವಹಾರದ ಹೆಸರು',
    'delivery_provision': 'ವಿತರಣೆ ಒದಗಿಸುವಿಕೆ',
    'phone_number': 'ಫೋನ್ ಸಂಖ್ಯೆ',
    'email_address': 'ಇಮೇಲ್ ವಿಳಾಸ',
    'address': 'ವಿಳಾಸ',
    'pin_code': 'ಪಿನ್ ಕೋಡ್',
    'use_current_location': 'ಪ್ರಸ್ತುತ ಸ್ಥಳವನ್ನು ಬಳಸಿ',
    'enter_phone': '10 ಅಂಕಿಗಳ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    'fill_required_fields': 'ಎಲ್ಲಾ ಅಗತ್ಯ ಕ್ಷೇತ್ರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ',
    'valid_phone_number': 'ಮಾನ್ಯ 10-ಅಂಕಿಯ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    'valid_email': 'ಮಾನ್ಯ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ',
    'fill_address_pincode': 'ಮುಂದುವರೆಯಲು ವಿಳಾಸ ಮತ್ತು ಪಿನ್ ಕೋಡ್ ಭರ್ತಿ ಮಾಡಿ',
    'welcome_donor': 'ಸ್ವಾಗತ ದಾನಿ',
    'total_donations': 'ಒಟ್ಟು ದಾನಗಳು',
    'donations_received': 'ಸ್ವೀಕರಿಸಿದ ದಾನಗಳು',
    'people_reached': 'ತಲುಪಿದ ಜನರು',
    'extra_food_message': 'ಹೆಚ್ಚುವರಿ ಆಹಾರವಿದೆಯೇ? ಅದನ್ನು ಅಗತ್ಯವಿರುವವರೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳಿ!',
    'create_donation_post': 'ದಾನ ಪೋಸ್ಟ್ ರಚಿಸಿ',
    'donation_history': 'ದಾನ ಇತಿಹಾಸ',
    'discussion': 'ಚರ್ಚೆ',
    'announcement': 'ಪ್ರಕಟಣೆ',
    'pending': 'ಬಾಕಿ',
    'donated': 'ದಾನ ಮಾಡಲಾಗಿದೆ',
    'chapati': 'ಚಪಾತಿ',
    'daal': 'ದಾಲ್',
    'rice': 'ಅಕ್ಕಿ',
    // Donor Create Page
    'create_donation': 'ದಾನ ರಚಿಸಿ',
    'add_title': 'ಶೀರ್ಷಿಕೆ ಸೇರಿಸಿ',
    'food_title': 'ಆಹಾರ ಶೀರ್ಷಿಕೆ',
    'ready_to_pickup': 'ಇದು ತೆಗೆದುಕೊಳ್ಳಲು ಸಿದ್ಧವಾಗಿದೆಯೇ?',
    'select_availability': 'ಲಭ್ಯತೆ ಆಯ್ಕೆಮಾಡಿ',
    'available': 'ಲಭ್ಯ',
    'not_available': 'ಲಭ್ಯವಿಲ್ಲ',
    'not_ready_to_pickup': 'ತೆಗೆದುಕೊಳ್ಳಲು ಸಿದ್ಧವಿಲ್ಲ',
    'describe_food_donation': 'ನಿಮ್ಮ ಆಹಾರ ದಾನವನ್ನು ವಿವರಿಸಿ...',
    'food_quantity': 'ಆಹಾರ ಪ್ರಮಾಣ',
    'veg': 'ಶಾಕಾಹಾರಿ',
    'non_veg': 'ಮಾಂಸಾಹಾರಿ',
    'photos': 'ಫೋಟೋಗಳು',
    'food_quality_assurance': 'ಆಹಾರದ ಗುಣಮಟ್ಟ ಮತ್ತು ನೈರ್ಮಲ್ಯದಿಂದ ರಾಜಿ ಮಾಡಿಕೊಳ್ಳಲಾಗಿಲ್ಲ ಎಂದು ನಾನು ಖಚಿತಪಡಿಸುತ್ತೇನೆ',
    'submit': 'ಸಲ್ಲಿಸಿ',
    'donation_success': 'ಅದ್ಭುತ! ನಿಮ್ಮ ದಾನ ವಿನಂತಿ ಯಶಸ್ವಿಯಾಗಿ ಪೋಸ್ಟ್ ಮಾಡಲಾಗಿದೆ',
    'back_to_home': 'ಹೋಮ್‌ಗೆ ಹಿಂತಿರುಗಿ',
    'fill_required_fields': 'ದಯವಿಟ್ಟು ಎಲ್ಲಾ ಅಗತ್ಯ ಕ್ಷೇತ್ರಗಳನ್ನು ಪೂರೈಸಿ',
    'volunteer_details': 'ಸ್ವಯಂಸೇವಕ ವಿವರಗಳು',
    'full_name': 'ಪೂರ್ಣ ಹೆಸರು',
    'occupation': 'ವೃತ್ತಿ',
    'aadhar_id': 'ಆಧಾರ್ ಐಡಿ',
    // Volunteer Home Page
    'welcome_volunteer': 'ಸ್ವಾಗತ ಸ್ವಯಂಸೇವಕ',
    'orders_delivered': 'ವಿತರಿಸಿದ ಆರ್ಡರ್‌ಗಳು',
    'feedback_received': 'ಸ್ವೀಕರಿಸಿದ ಪ್ರತಿಕ್ರಿಯೆ',
    'points_earned': 'ಗಳಿಸಿದ ಅಂಕಗಳು',
    'available_donations': 'ಲಭ್ಯ ದಾನಗಳು',
    'view_more': '+ ಹೆಚ್ಚು ನೋಡಿ',
    'show_less': '- ಕಡಿಮೆ ತೋರಿಸಿ',
    'community': 'ಸಮುದಾಯ',
    'discussion': 'ಚರ್ಚೆ',
    'announcement': 'ಪ್ರಕಟಣೆ',
    'discussion_description': 'ಹಲೋ ಎಲ್ಲರಿಗೂ, ನಾನು ರೆಸ್ಟೋರೆಂಟ್ ನಡೆಸುತ್ತೇನೆ ಮತ್ತು ಮುಚ್ಚುವ ಸಮಯದಲ್ಲಿ ಹೆಚ್ಚಾಗಿ ಉಳಿದ ಆಹಾರವಿರುತ್ತದೆ. ದಾನ ಮಾಡುವ ಮೊದಲು ಆಹಾರವನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಸಂಗ್ರಹಿಸಲು ಉತ್ತಮ ಅಭ್ಯಾಸಗಳು ಯಾವುವು',
    'announcement_description': 'ನಾವು ಆಹಾರ ದಾನಗಳಲ್ಲಿ ಹೆಚ್ಚಳವನ್ನು ನೋಡಿದ್ದೇವೆ, ಆದರೆ ಬೆಂಗಳೂರಿನಲ್ಲಿ ಪಿಕ್-ಅಪ್ ಮತ್ತು ವಿತರಣೆಗಾಗಿ ಹೆಚ್ಚಿನ ಸ್ವಯಂಸೇವಕರ ಅಗತ್ಯವಿದೆ. ನಿಮಗೆ ಆಸಕ್ತಿ ಇದ್ದರೆ, ದಯವಿಟ್ಟು ನಮ್ಮ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    // Receiver Home Page
    'requests_made': 'ಮಾಡಿದ ವಿನಂತಿಗಳು',
    'requests_fulfilled': 'ಪೂರ್ಣಗೊಂಡ ವಿನಂತಿಗಳು',
    'people_helped': 'ಸಹಾಯ ಮಾಡಿದ ಜನರು',
    'user_login': 'ಬಳಕೆದಾರ ಲಾಗಿನ್',
    'hero_title': 'ರಕ್ಷಿಸಿ. ಹಂಚಿಕೊಳ್ಳಿ. ಪೌಷ್ಟಿಕತೆ ನೀಡಿ.',
    'hero_subtitle': 'ಯಾವುದೇ ಊಟವೂ ವ್ಯರ್ಥವಾಗಬಾರದು!',
    'need_meal_prompt': 'ಊಟಕ್ಕೆ ಅಗತ್ಯವಿರುವ ಯಾರಾದರೂ ತಿಳಿದಿದ್ದಾರೆಯೇ?',
    'create_food_request': 'ಆಹಾರ ವಿನಂತಿ ರಚಿಸಿ',
    'request_history': 'ವಿನಂತಿ ಇತಿಹಾಸ',
    'food_request_details': 'ಆಹಾರ ವಿನಂತಿ ವಿವರಗಳು',
    'no_of_beneficiaries': 'ಲಾಭಾರ್ಥಿಗಳ ಸಂಖ್ಯೆ',
    'enter_beneficiaries': 'ಲಾಭಾರ್ಥಿಗಳ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    'beneficiary_details': 'ಲಾಭಾರ್ಥಿ ವಿವರಗಳು (ಐಚ್ಛಿಕ)',
    'name': 'ಹೆಸರು',
    'need_food_example': 'ಉದಾ: 50 ಜನರಿಗೆ ಆಹಾರ ಬೇಕು.',
    'contact_details': 'ಸಂಪರ್ಕ ವಿವರಗಳು',
    'request_success': 'ಅದ್ಭುತ! ನಿಮ್ಮ ಆಹಾರ ವಿನಂತಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ',
    'enter_full_name': 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    'enter_occupation': 'ನಿಮ್ಮ ವೃತ್ತಿಯನ್ನು ನಮೂದಿಸಿ',
    'enter_aadhar': 'ನಿಮ್ಮ ಆಧಾರ್ ಐಡಿಯನ್ನು ನಮೂದಿಸಿ',
    'enter_address': 'ನಿಮ್ಮ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ',
    'enter_pincode': 'ನಿಮ್ಮ ಪಿನ್ ಕೋಡ್ ಅನ್ನು ನಮೂದಿಸಿ',
    'enter_org_name': 'ಸಂಸ್ಥೆಯ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    'enter_delivery_provision': 'ವಿತರಣೆ ಒದಗಿಸುವಿಕೆ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ',
    'enter_email': 'ನಿಮ್ಮ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ',
    'personal_info': 'ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ',
    'organization_info': 'ಸಂಸ್ಥೆಯ ಮಾಹಿತಿ',
    'address_info': 'ವಿಳಾಸ ಮಾಹಿತಿ',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 